# Generated by Django 5.0.4 on 2025-08-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
