# Generated by Django 5.0.4 on 2025-08-27 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0002_patient_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('doctor_name', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosp.patient')),
            ],
        ),
    ]


