# Generated by Django 5.0.4 on 2025-10-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0005_appointment_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='token_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
