# Generated by Django 5.0.4 on 2026-06-19 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hosp.patient'),
        ),
    ]
