# Generated by Django 5.0.4 on 2026-06-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0008_feedback_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
