# Generated by Django 5.0.4 on 2026-06-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0009_delete_medicalrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor_name',
            new_name='service_name',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='doctor_or_service',
            new_name='service_name',
        ),
    ]
